ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER C##djangoadmi IDENTIFIED BY passora;
GRANT CONNECT TO C##djangoadmi;
GRANT RESOURCE TO C##djangoadmi;
ALTER USER C##djangoadmi DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; 
GRANT CREATE SEQUENCE TO C##djangoadmi;
GRANT CREATE VIEW TO C##djangoadmi;