ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER C##djangoadmi11 IDENTIFIED BY passora;
GRANT CONNECT TO C##djangoadmi11;
GRANT RESOURCE TO C##djangoadmi11;
ALTER USER C##djangoadmi11 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS; 
GRANT CREATE SEQUENCE TO C##djangoadmi11;
GRANT CREATE VIEW TO C##djangoadmi11;
